Models/Computer.cs
namespace MvcLabManager.Models;

public class Computer
{
    public int Id { get; set; }
    public string Ram { get; set; }
    public string Processor { get; set; }

    public Computer() { }

    public Computer(int id, string ram, string processor)
    {
        Id = id;
        Ram = ram;
        Processor = processor;
    }
}

Models/ErrorViewModel.cs
namespace MvcLabManager.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/Lab.cs
namespace MvcLabManager.Models;

public class Lab
{
    public int Id { get; set; }
    public int Number { get; set; }
    public string Name { get; set; }
    public string Block { get; set; }

    public Lab() { }

    public Lab(int id, int number, string name, string block)
    {
        Id = id;
        Number = number;
        Name = name;
        Block = block;
    }
}

Models/LabManagerContext.cs
using Microsoft.EntityFrameworkCore;

namespace MvcLabManager.Models;

public class LabManagerContext : DbContext
{
    public DbSet<Computer> Computers { get; set; }
    public DbSet<Lab> Labs { get; set; }

    public LabManagerContext(DbContextOptions<LabManagerContext> options) : base(options)
    {
        
    }
}

Controllers/ComputerController.cs
using Microsoft.AspNetCore.Mvc;
using MvcLabManager.Models;

namespace MvcLabManager.Controllers;

public class ComputerController : Controller
{
    private readonly LabManagerContext _context;

    public ComputerController(LabManagerContext context)
    {
        _context = context;
    }

    public IActionResult Index()
    {
        return View(_context.Computers);
    }

    public IActionResult Show(int id)
    {
        Computer computer = _context.Computers.Find(id);

        if(computer == null)
        {
            return NotFound();
        }

        return View(computer);
    }

    public IActionResult Cadastro()
    {
        return View();
    }

    public IActionResult Cadastrando([FromForm] int id, [FromForm] string ram, [FromForm] string processor)
    {
        if(_context.Computers.Find(id) != null)
        {
            return View(id);
        }
        else
        {
             _context.Computers.Add(new Computer(id, ram, processor));
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

    }

    public IActionResult Update([FromForm] int id, [FromForm] string ram, [FromForm] string processor)
    {
         Computer computer = _context.Computers.Find(id);

        if(computer != null)
        {
            computer.Ram = ram;
            computer.Processor = processor;
            _context.Computers.Update(computer);
            _context.SaveChanges();
        }
        return RedirectToAction("Index");
    }

    public IActionResult Atualizacao(int id)
    {
        Computer computer = _context.Computers.Find(id);

        if(computer == null)
        {
            return NotFound();
        }

        return View(computer);
    }

    public IActionResult Delete(int id)
    {
        _context.Computers.Remove(_context.Computers.Find(id));
        _context.SaveChanges();
        return RedirectToAction("Index");
    }

}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using MvcLabManager.Models;

namespace MvcLabManager.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/LabController.cs
using Microsoft.AspNetCore.Mvc;
using MvcLabManager.Models;

namespace MvcLabManager.Controllers;

public class LabController : Controller
{
    private readonly LabManagerContext _context;

    public LabController(LabManagerContext context) {
        _context = context;
    }

    public IActionResult Index()
    {
        return View(_context.Labs);
    }

    public IActionResult Show(int id)
    {
        Lab lab = _context.Labs.Find(id);

        if(lab == null)
        {
            return NotFound();
        }

        return View(lab);
    }

    public IActionResult Delete(int id)
    {
        _context.Labs.Remove(_context.Labs.Find(id));
        _context.SaveChanges();
        return RedirectToAction("Index");
    }

    public IActionResult Cadastro()
    {
        return View();
    }

    public IActionResult Cadastrando([FromForm] int id, [FromForm] int number, [FromForm] string name, [FromForm] string block)
    {
        if(_context.Labs.Find(id) != null)
        {
            return View(id);
        }
        else
        {
            _context.Labs.Add(new Lab(id, number, name, block));
            _context.SaveChanges();

            return RedirectToAction("Index");
        }
    }

    public IActionResult Atualizacao(int id)
    {
        Lab lab = _context.Labs.Find(id);

        if(lab == null)
        {
            return NotFound();
        }

        return View(lab);
    }

    public IActionResult Update([FromForm] int id, [FromForm] int number, [FromForm] string name, [FromForm] string block)
    {
        Lab lab = _context.Labs.Find(id);

        if(lab != null)
        {
            lab.Number = number;
            lab.Name = name;
            lab.Block = block;
            _context.Labs.Update(lab);
            _context.SaveChanges();
        }
        return RedirectToAction("Index");
    }
}

Views/Computer/Atualizacao.cshtml
@model MvcLabManager.Models.Computer

@{
    ViewData["Title"] = "Atualização de Computador";
}
<a href="/Computer/Show/@Model.Id" class="btn btn-primary btn-sm btn-light">Voltar</a><br><br>
<h1>@ViewData["Title"] @Model.Id</h1><br>

<form action="/Computer/Update" method="post">
    <table>
        <tr>
            <td><label for="id">Id:&nbsp;&nbsp;&nbsp;</label></td>
            <td><input type="number" name="id" id="id" value="@Model.Id" readonly></td>
        </tr>
        <tr>
            <td><label for="ram">Memória RAM:</label></td>
            <td><input type="text" name="ram" id="ram" required> GB</td>
        </tr>
        <tr>
            <td><label for="processor">Processador:</label></td>
            <td><input type="text" name="processor" id="processor" required></td>
        </tr>
    </table><br>
    <input type="submit" class="btn btn-primary btn-sm btn-success" value="Atualizar">
</form>

Views/Computer/Cadastrando.cshtml
@{
    ViewData["Title"] = "Erro de cadastro";
}
<a href="/Computer/Index" class="btn btn-primary btn-sm btn-light">Voltar</a><br><br>
<h1>@ViewData["Title"]</h1>

<p>O computador com o Id @Model já foi cadastrado.</p>

Views/Computer/Cadastro.cshtml
@{
    ViewData["Title"] = "Cadastrar do Computador";
}
<a href="/Computer/Index" class="btn btn-primary btn-sm btn-light">Voltar</a><br><br>
<h1>@ViewData["Title"]</h1><br>

<form action="/Computer/Cadastrando" method="post">
    <table>
        <tr>
            <td><label for="id">Id:&nbsp;&nbsp;&nbsp;</label></td>
            <td><input type="number" name="id" id="id" required></td>
        </tr>
        <tr>
            <td><label for="ram">Memória RAM:</label></td>
            <td><input type="text" name="ram" id="ram" required> GB</td>
        </tr>
        <tr>
            <td><label for="processor">Processador:</label></td>
            <td><input type="text" name="processor" id="processor" required></td>
        </tr>
    </table><br>
    <input type="submit" class="btn btn-primary btn-sm btn-success" value="Cadastrar">
</form>

Views/Computer/Index.cshtml
@model IEnumerable<MvcLabManager.Models.Computer>

@{
    ViewData["Title"] = "Computadores";
}
<h1>@ViewData["Title"]</h1>

@if(Model.Count() == 0)
{
    <p>Nenhum computador cadastrado</p>
}
else
{
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Ram</th>
                <th>Processor</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var computer in Model)
            {
            <tr>
                <td>@computer.Id</td>
                <td>@computer.Ram</td>
                <td>@computer.Processor</td>
                <td>
                    <a 
                    href="/Computer/Show/@computer.Id" class="btn btn-primary btn-sm">Ver
                    </a>
                </td>
            </tr>
            }
        </tbody>
    </table>
}

Views/Computer/Show.cshtml
@model MvcLabManager.Models.Computer

@{
    ViewData["Title"] = $"Computador {Model.Id}";
}
<a href="/Computer/Index" class="btn btn-primary btn-sm btn-light">< Voltar</a>
<h1>@ViewData["Title"]</h1>

<p><b>Id:</b>@Model.Id</p>
<p><b>Ram:</b>@Model.Ram</p>
<p><b>Processor:</b>@Model.Processor</p>
<p><a href="/Computer/Atualizacao/@Model.Id" class="btn btn-primary btn-sm btn-dark">Atualizar</a>&nbsp;&nbsp;<a href="/Computer/Delete/@Model.Id" class="btn btn-primary btn-sm btn-danger">Excluir</a></p>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Lab/Atualizacao.cshtml
@model MvcLabManager.Models.Lab

@{
    ViewData["Title"] = "Atualização de Laboratório";
}
<a href="/Lab/Show/@Model.Id" class="btn btn-primary btn-sm btn-light">Voltar</a><br><br>
<h1>@ViewData["Title"] @Model.Id</h1><br>

<form action="/Lab/Update" method="post">
    <table>
        <tr>
            <td><label for="id">Id:&nbsp;&nbsp;&nbsp;</label></td>
            <td><input type="number" name="id" id="id" value="@Model.Id" readonly></td>
        </tr>
        <tr>
            <td><label for="number">Número:</label></td>
            <td><input type="number" name="number" id="number" required> GB</td>
        </tr>
        <tr>
            <td><label for="name">Nome:</label></td>
            <td><input type="text" name="name" id="name" required></td>
        </tr>
        <tr>
            <td><label for="block">Bloco:</label></td>
            <td><input type="text" name="block" id="block" required></td>
        </tr>
    </table><br>
    <input type="submit" class="btn btn-primary btn-sm btn-success" value="Atualizar">
</form>

Views/Lab/Cadastrando.cshtml
@model int

@{
    ViewData["Title"] = "Erro de Cadastro";
}
<a href="/Lab/Index" class="btn btn-primary btn-sm btn-light">Voltar</a><br><br>
<h1>@ViewData["Title"]</h1><br>

<p>O laboratório com Id @Model já foi cadastrado.</p>

Views/Lab/Cadastro.cshtml
@{
    ViewData["Title"] = "Cadastro de Laboratório";
}
<a href="/Lab/Index" class="btn btn-primary btn-sm btn-light">Voltar</a><br><br>
<h1>@ViewData["Title"]</h1><br>

<form action="/Lab/Cadastrando" method="post">
    <table>
        <tr>
            <td><label for="id">Id:&nbsp;&nbsp;&nbsp;</label></td>
            <td><input type="number" name="id" id="id" required></td>
        </tr>
        <tr>
            <td><label for="number">Número:</label></td>
            <td><input type="number" name="number" id="number" required> GB</td>
        </tr>
        <tr>
            <td><label for="name">Nome:</label></td>
            <td><input type="text" name="name" id="name" required></td>
        </tr>
        <tr>
            <td><label for="block">Bloco:</label></td>
            <td><input type="text" name="block" id="block" required></td>
        </tr>
    </table><br>
    <input type="submit" class="btn btn-primary btn-sm btn-success" value="Cadastrar">
</form>

Views/Lab/Index.cshtml
@model IEnumerable<MvcLabManager.Models.Lab>

@{
    ViewData["Title"] = "Laboratórios";
}

<h1>@ViewData["Title"]</h1>

@if(Model.Count() == 0)
{
    <table class="table">
        <tr><td><center>Nenhum laboratório foi cadastrado!</center></td></tr>
        <tr><td><center><a href="/Lab/Cadastro" class="btn btn-sm btn-outline-success">+</a></center></td></tr>
    </table>
}
else
{
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Número</th>
                <th>Nome</th>
                <th>Bloco</th>
                <th>Detalhes</th>
            </tr>
        </thead>
        <tbody>
            @foreach(var lab in Model){
                <tr>
                    <td>@lab.Id</td>
                    <td>@lab.Number</td>
                    <td>@lab.Name</td>
                    <td>@lab.Block</td>
                    <td><a href="/Lab/Show/@lab.Id" class="btn btn-primary btn-sm btn-dark">Ver</a></td>
                </tr>
            }
            <tr>
                <td colspan="5"><center><a href="/Lab/Cadastro" class="btn btn-sm btn-outline-success">+</a></center></td>
            </tr>
        </tbody>
    </table>
}

Views/Lab/Show.cshtml
@model MvcLabManager.Models.Lab

@{
    ViewData["Title"] = $"Laboratório {Model.Id}";
}
<a href="/Lab/Index" class="btn btn-primary btn-sm btn-light">< Voltar</a>
<h1>@ViewData["Title"]</h1>

<p><b>Id: </b> @Model.Id</p>
<p><b>Número: </b> @Model.Number</p>
<p><b>Nome: </b> @Model.Name</p>
<p><b>Bloco: </b> @Model.Block</p>
<p><a href="/Lab/Atualizacao/@Model.Id" class="btn btn-primary btn-sm btn-dark">Atualizar</a>&nbsp;&nbsp;<a href="/Lab/Delete/@Model.Id" class="btn btn-primary btn-sm btn-danger">Excluir</a></p>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcLabManager</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcLabManager.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcLabManager</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Computer" asp-action="Index">Computer</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Lab" asp-action="Index">Lab</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MvcLabManager - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>